export const CONSTANTS = {
    GET_TODOS:'GET_TODOS',
    GET_TODO_ITEM:'GET_TODO_ITEM',
    POST_TODO_ITEM:'POST_TODO_ITEM',
    UPDATE_TODO_ITEM:'UPDATE_TODO_ITEM',
    DELETE_TODO_ITEM:'DELETE_TODO_ITEM',
    DELETE_TODOS:'DELETE_TODOS'
}

export default CONSTANTS;